{
  "formatVersion": "1.1",
  "component": {
    "group": "cool.heller.uli",
    "module": "hello-world",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hello-world-0.1.0-plain.jar",
          "url": "hello-world-0.1.0-plain.jar",
          "size": 781,
          "sha512": "64cd746a7324e55199ddf4587880c2f4724da0f682b5aa95483e3d8d4be645d23b458981f91f57eabbc6134e18697fba2744bb19ce67b0e2a816445eb69283a0",
          "sha256": "3d9ff454ebefe6833c0169714aa03893bd3e86afc216edd039ab345163a83e73",
          "sha1": "32b912444a4261b14525a7ee4514d0e6a901d1b7",
          "md5": "936634bab69f1bd481b7c15651164cdb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.4.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        }
      ],
      "files": [
        {
          "name": "hello-world-0.1.0-plain.jar",
          "url": "hello-world-0.1.0-plain.jar",
          "size": 781,
          "sha512": "64cd746a7324e55199ddf4587880c2f4724da0f682b5aa95483e3d8d4be645d23b458981f91f57eabbc6134e18697fba2744bb19ce67b0e2a816445eb69283a0",
          "sha256": "3d9ff454ebefe6833c0169714aa03893bd3e86afc216edd039ab345163a83e73",
          "sha1": "32b912444a4261b14525a7ee4514d0e6a901d1b7",
          "md5": "936634bab69f1bd481b7c15651164cdb"
        }
      ]
    }
  ]
}
